# JWT Configuration
jwt:
  secret: ${{ secrets.JWT_SECRET }}
  expiration: 900_000 # 15 minutes
  issuer: "Obsidi Academy"
  audience: feedApp
  prefix: "Bearer "
  excluded.urls: >
    /user/login,
    /user/signup,
    /user/reset/*,
    /test/**,
    /error,

# Client Configuration
client:
  url: http://localhost:3000
  email:
    verify:
      param: user/verifyEmail
      expiration: 86_400_000 # 24 hours
    reset:
      param: user/resetPassword
      expiration: 600_000 # 10 minutes
